rd /s/q 'G:\comic\src\res\1.2三四郎2' 
rd /s/q 'G:\comic\src\res\15 November' 
rd /s/q 'G:\comic\src\res\1518！' 
rd /s/q 'G:\comic\src\res\15人明刹工业高中橄榄球部' 
rd /s/q 'G:\comic\src\res\15美少女漂流记' 
rd /s/q 'G:\comic\src\res\1602' 
rd /s/q 'G:\comic\src\res\16bit的感动' 
rd /s/q 'G:\comic\src\res\16LIFE' 
rd /s/q 'G:\comic\src\res\16岁的指南书' 
rd /s/q 'G:\comic\src\res\16岁的新婚' 
rd /s/q 'G:\comic\src\res\16岁，近江之夏' 
rd /s/q 'G:\comic\src\res\17' 
rd /s/q 'G:\comic\src\res\17.毕业前夕' 
rd /s/q 'G:\comic\src\res\17岁℃' 
rd /s/q 'G:\comic\src\res\17岁亲吻和进退两难' 
rd /s/q 'G:\comic\src\res\17岁千金的初恋' 
rd /s/q 'G:\comic\src\res\17岁夏之恋' 
rd /s/q 'G:\comic\src\res\17岁女子高生监禁杀人' 
rd /s/q 'G:\comic\src\res\17岁的Paradox' 
rd /s/q 'G:\comic\src\res\17岁的夏天' 
rd /s/q 'G:\comic\src\res\17岁的妈妈' 
rd /s/q 'G:\comic\src\res\17岁的秘密恋情' 
rd /s/q 'G:\comic\src\res\17岁的秘密情欲' 
rd /s/q 'G:\comic\src\res\17岁美少女' 
rd /s/q 'G:\comic\src\res\17岁革命' 
rd /s/q 'G:\comic\src\res\17年未了情' 
rd /s/q 'G:\comic\src\res\17种性幻想 情侣游戏' 
rd /s/q 'G:\comic\src\res\17青春遁走' 
rd /s/q 'G:\comic\src\res\1827夏日大作战' 
rd /s/q 'G:\comic\src\res\18m2的秘密基地' 
rd /s/q 'G:\comic\src\res\18Rin' 
rd /s/q 'G:\comic\src\res\18岁的暑假' 
rd /s/q 'G:\comic\src\res\18岁的鼓动' 
rd /s/q 'G:\comic\src\res\18禁' 
rd /s/q 'G:\comic\src\res\1921' 
rd /s/q 'G:\comic\src\res\1925' 
rd /s/q 'G:\comic\src\res\1999上海夜未眠' 
rd /s/q 'G:\comic\src\res\19岁为爱不顾一切' 
rd /s/q 'G:\comic\src\res\1DK的幸福' 
rd /s/q 'G:\comic\src\res\1K的王様' 
rd /s/q 'G:\comic\src\res\1LOVE9' 
rd /s/q 'G:\comic\src\res\1or8' 
rd /s/q 'G:\comic\src\res\1st Summer' 
rd /s/q 'G:\comic\src\res\1_2英雄' 
rd /s/q 'G:\comic\src\res\1克拉女孩' 
rd /s/q 'G:\comic\src\res\1区212' 
rd /s/q 'G:\comic\src\res\1年5组生物小队' 
rd /s/q 'G:\comic\src\res\1年A班的怪物' 
rd /s/q 'G:\comic\src\res\2.14事件' 
rd /s/q 'G:\comic\src\res\2.5次元的诱惑' 
rd /s/q 'G:\comic\src\res\2000年之吻' 
rd /s/q 'G:\comic\src\res\2001夜物语' 
rd /s/q 'G:\comic\src\res\2003年集英社漫画巡礼' 
rd /s/q 'G:\comic\src\res\2013年秋作战' 
rd /s/q 'G:\comic\src\res\2014贺正' 
rd /s/q 'G:\comic\src\res\2015年的冬木市' 
rd /s/q 'G:\comic\src\res\201室的井森小姐【蝾螈201】' 
rd /s/q 'G:\comic\src\res\202号室的魔法使' 
rd /s/q 'G:\comic\src\res\20⑨2' 
rd /s/q 'G:\comic\src\res\20世纪传说' 
rd /s/q 'G:\comic\src\res\20世纪少年' 
rd /s/q 'G:\comic\src\res\20世纪少年的配角' 
rd /s/q 'G:\comic\src\res\21世纪小福星' 
rd /s/q 'G:\comic\src\res\21世纪少年' 
rd /s/q 'G:\comic\src\res\21公克的心意' 
rd /s/q 'G:\comic\src\res\21卫门' 
rd /s/q 'G:\comic\src\res\24h Honey' 
rd /s/q 'G:\comic\src\res\24H爱的行进' 
rd /s/q 'G:\comic\src\res\24H爱的进行' 
rd /s/q 'G:\comic\src\res\24twenty-four非日常' 
rd /s/q 'G:\comic\src\res\24小时恋爱中' 
rd /s/q 'G:\comic\src\res\24小时营业中' 
rd /s/q 'G:\comic\src\res\25cm的远距离' 
rd /s/q 'G:\comic\src\res\25小时的捉迷藏' 
rd /s/q 'G:\comic\src\res\25度的咖啡' 
rd /s/q 'G:\comic\src\res\26cm的玻璃鞋' 
rd /s/q 'G:\comic\src\res\27岁的你我她' 
rd /s/q 'G:\comic\src\res\27时喃喃恋语' 
rd /s/q 'G:\comic\src\res\28岁的少女漫画脑哥哥和16岁的BL漫画脑妹妹的二三事' 
rd /s/q 'G:\comic\src\res\29与JK ～社令难违牵手女高中生' 
rd /s/q 'G:\comic\src\res\29岁单身冒险家的日常' 
rd /s/q 'G:\comic\src\res\29岁的单身狗想在异世界追求自由大放异彩！！' 
rd /s/q 'G:\comic\src\res\2DK、G笔、闹钟。' 
rd /s/q 'G:\comic\src\res\2LDK发生的恋情' 
rd /s/q 'G:\comic\src\res\2LJK' 
rd /s/q 'G:\comic\src\res\2X2的交错恋情' 
rd /s/q 'G:\comic\src\res\2x2风云双胞胎' 
rd /s/q 'G:\comic\src\res\2×2 ROOM' 
rd /s/q 'G:\comic\src\res\2丁目的小小鱼' 
rd /s/q 'G:\comic\src\res\2人心世界' 
rd /s/q 'G:\comic\src\res\2周的冒险假期' 
rd /s/q 'G:\comic\src\res\2图系列' 
rd /s/q 'G:\comic\src\res\2小时21分的恋人' 
rd /s/q 'G:\comic\src\res\2岁的Love Star' 
rd /s/q 'G:\comic\src\res\2年G组千坂千阳男友募集' 
rd /s/q 'G:\comic\src\res\2楼的玛莉亚' 
rd /s/q 'G:\comic\src\res\3.11纪念短篇' 
rd /s/q 'G:\comic\src\res\30' 
rd /s/q 'G:\comic\src\res\30岁保健体育 恋爱升级' 
rd /s/q 'G:\comic\src\res\30岁左右的初恋' 
rd /s/q 'G:\comic\src\res\30秒怪奇妙恐怖故事' 
rd /s/q 'G:\comic\src\res\31厘米的抑郁' 
rd /s/q 'G:\comic\src\res\337应援男' 
rd /s/q 'G:\comic\src\res\34岁无业小姐' 
rd /s/q 'G:\comic\src\res\35度恋爱热' 
rd /s/q 'G:\comic\src\res\36.5℃' 
rd /s/q 'G:\comic\src\res\36.5℃的天使' 
rd /s/q 'G:\comic\src\res\36.5℃的手心' 
rd /s/q 'G:\comic\src\res\36.7°' 
rd /s/q 'G:\comic\src\res\36.7摄氏度' 
rd /s/q 'G:\comic\src\res\360完美世界' 
rd /s/q 'G:\comic\src\res\365 End Roll' 
rd /s/q 'G:\comic\src\res\365步的棋王' 
rd /s/q 'G:\comic\src\res\37°C你是我的最爱' 
rd /s/q 'G:\comic\src\res\37℃烈酒' 
rd /s/q 'G:\comic\src\res\3D彼女' 
rd /s/q 'G:\comic\src\res\3LDK的国王' 
rd /s/q 'G:\comic\src\res\3Peace' 
rd /s/q 'G:\comic\src\res\3x3Eyes' 
rd /s/q 'G:\comic\src\res\3X8等于24笑' 
rd /s/q 'G:\comic\src\res\3万日元的男友' 
rd /s/q 'G:\comic\src\res\3个人一起好吗' 
rd /s/q 'G:\comic\src\res\3个谎言' 
rd /s/q 'G:\comic\src\res\3人游戏' 
rd /s/q 'G:\comic\src\res\3亿元之恋' 
rd /s/q 'G:\comic\src\res\3秒陷入爱情' 
rd /s/q 'G:\comic\src\res\4 Colors＊4 Frames' 
rd /s/q 'G:\comic\src\res\404小队故事' 
rd /s/q 'G:\comic\src\res\404小队的欢乐日常！' 
rd /s/q 'G:\comic\src\res\4213mg配合のきもち' 
rd /s/q 'G:\comic\src\res\42岁开始当美少女侦探' 
rd /s/q 'G:\comic\src\res\45 degree eyebrows' 
rd /s/q 'G:\comic\src\res\461个便当，老爸与儿子男人间的约定' 
rd /s/q 'G:\comic\src\res\48手读本' 
rd /s/q 'G:\comic\src\res\49' 
rd /s/q 'G:\comic\src\res\49－你是我的唯一' 
rd /s/q 'G:\comic\src\res\4D' 
rd /s/q 'G:\comic\src\res\4修生也恋爱' 
rd /s/q 'G:\comic\src\res\4分钟料理' 
rd /s/q 'G:\comic\src\res\4这个！2瑞鹤和加贺女士的书' 
rd /s/q 'G:\comic\src\res\4／365恋人' 
rd /s/q 'G:\comic\src\res\5.5企化的爱情攻势' 
rd /s/q 'G:\comic\src\res\500年的依恋' 
rd /s/q 'G:\comic\src\res\500年的爱恋' 
rd /s/q 'G:\comic\src\res\500镑的噗酱' 
rd /s/q 'G:\comic\src\res\50X50' 
rd /s/q 'G:\comic\src\res\50×50双向情人' 
rd /s/q 'G:\comic\src\res\520.千纸鹤' 
rd /s/q 'G:\comic\src\res\55-雪' 
rd /s/q 'G:\comic\src\res\55号' 
rd /s/q 'G:\comic\src\res\5Seconds' 
rd /s/q 'G:\comic\src\res\5th' 
rd /s/q 'G:\comic\src\res\5X100' 
rd /s/q 'G:\comic\src\res\5人之王' 
rd /s/q 'G:\comic\src\res\5岁无表情 心酱常苦悲' 
rd /s/q 'G:\comic\src\res\5点后KISS雨系列7' 
rd /s/q 'G:\comic\src\res\5点后KISS雨系列Ⅰ五点钟后的亲密之吻' 
rd /s/q 'G:\comic\src\res\5点后KISS雨系列Ⅱ百万顿之爱' 
rd /s/q 'G:\comic\src\res\5点后KISS雨系列Ⅲ在梦中相会吧' 
rd /s/q 'G:\comic\src\res\5点后KISS雨系列Ⅳ许我一个他' 
rd /s/q 'G:\comic\src\res\5点后KISS雨系列Ⅴ爱情Only You' 
rd /s/q 'G:\comic\src\res\6.3.3再录本' 
rd /s/q 'G:\comic\src\res\666撒旦' 
rd /s/q 'G:\comic\src\res\69时限极道男' 
rd /s/q 'G:\comic\src\res\69蜜友' 
rd /s/q 'G:\comic\src\res\6cm的自尊心' 
rd /s/q 'G:\comic\src\res\6LDK～大型犬入住～' 
rd /s/q 'G:\comic\src\res\6mm禁忌' 
rd /s/q 'G:\comic\src\res\6厘米的羁绊' 
rd /s/q 'G:\comic\src\res\6月的弗雷德里克' 
rd /s/q 'G:\comic\src\res\7 s守护凪咲' 
rd /s/q 'G:\comic\src\res\70亿之针' 
rd /s/q 'G:\comic\src\res\70岁的初产' 
rd /s/q 'G:\comic\src\res\72机车魂' 
rd /s/q 'G:\comic\src\res\765偶像英豪传' 
rd /s/q 'G:\comic\src\res\777' 
rd /s/q 'G:\comic\src\res\777新战士' 
rd /s/q 'G:\comic\src\res\7与谎言Online' 
rd /s/q 'G:\comic\src\res\7岁差彼女' 
rd /s/q 'G:\comic\src\res\7年后的同居人' 
rd /s/q 'G:\comic\src\res\7时间目的音符' 
rd /s/q 'G:\comic\src\res\7月魔法使' 
rd /s/q 'G:\comic\src\res\7金刚' 
rd /s/q 'G:\comic\src\res\7驱合同志' 
rd /s/q 'G:\comic\src\res\7：32在第七节车厢的你' 
rd /s/q 'G:\comic\src\res\8-EIGHT-' 
rd /s/q 'G:\comic\src\res\8.1山田悠介剧场' 
rd /s/q 'G:\comic\src\res\80 decade' 
rd /s/q 'G:\comic\src\res\800米的彩虹' 
rd /s/q 'G:\comic\src\res\8059同人本' 
rd /s/q 'G:\comic\src\res\80℃' 
rd /s/q 'G:\comic\src\res\86- Eighty Six -' 
rd /s/q 'G:\comic\src\res\87超频者' 
rd /s/q 'G:\comic\src\res\88音符的黑白恋' 
rd /s/q 'G:\comic\src\res\8LDK -死者之王-' 
rd /s/q 'G:\comic\src\res\8叠间里的跃舞嘉年华' 
rd /s/q 'G:\comic\src\res\8号牢房' 
rd /s/q 'G:\comic\src\res\8回生俱乐部' 
rd /s/q 'G:\comic\src\res\8月的晕染' 
rd /s/q 'G:\comic\src\res\8月的苏打水' 
rd /s/q 'G:\comic\src\res\8月的魔物' 
rd /s/q 'G:\comic\src\res\9 Love Letters' 
rd /s/q 'G:\comic\src\res\90后向前冲' 
rd /s/q 'G:\comic\src\res\978-4' 
rd /s/q 'G:\comic\src\res\99' 
rd /s/q 'G:\comic\src\res\99 happy soul' 
rd /s/q 'G:\comic\src\res\9999999' 
rd /s/q 'G:\comic\src\res\999神传奇' 
rd /s/q 'G:\comic\src\res\9nine 九个 九日 九色，第一章，九条都宣传四格' 
rd /s/q 'G:\comic\src\res\9S' 
rd /s/q 'G:\comic\src\res\9号杀手' 
rd /s/q 'G:\comic\src\res\9年不遇的假日' 
rd /s/q 'G:\comic\src\res\9月-september' 
rd /s/q 'G:\comic\src\res\9次沈睡' 
rd /s/q 'G:\comic\src\res\9的神灵澡堂工作' 
rd /s/q 'G:\comic\src\res\9级降魔团队' 
rd /s/q 'G:\comic\src\res\A' 
rd /s/q 'G:\comic\src\res\A Beautiful Greed' 
rd /s/q 'G:\comic\src\res\A Channel' 
rd /s/q 'G:\comic\src\res\a fat lot you know' 
rd /s/q 'G:\comic\src\res\A fly boy' 
rd /s/q 'G:\comic\src\res\a lily of the vally' 
rd /s/q 'G:\comic\src\res\A plus X' 
rd /s/q 'G:\comic\src\res\A Strereo Love' 
rd /s/q 'G:\comic\src\res\A Sweet Nightmare' 
rd /s/q 'G:\comic\src\res\A TO Z' 
rd /s/q 'G:\comic\src\res\A Will' 
rd /s/q 'G:\comic\src\res\A+' 
rd /s/q 'G:\comic\src\res\A-RISE的翼队想和果果dancing dancing' 
rd /s/q 'G:\comic\src\res\A.I少女' 
rd /s/q 'G:\comic\src\res\A.S.野性第六感' 
rd /s/q 'G:\comic\src\res\AAA' 
rd /s/q 'G:\comic\src\res\Abandoned life' 
rd /s/q 'G:\comic\src\res\ABARA' 
rd /s/q 'G:\comic\src\res\abba-小包裹' 
rd /s/q 'G:\comic\src\res\AbilityShop' 
rd /s/q 'G:\comic\src\res\ACARIA' 
rd /s/q 'G:\comic\src\res\Access' 
rd /s/q 'G:\comic\src\res\accord' 
rd /s/q 'G:\comic\src\res\ACID GROOVE BODY DRIVER' 
rd /s/q 'G:\comic\src\res\ACID TOWN' 
rd /s/q 'G:\comic\src\res\ACONY' 
rd /s/q 'G:\comic\src\res\Action 芊面人生' 
rd /s/q 'G:\comic\src\res\ACUTE' 
rd /s/q 'G:\comic\src\res\ADAMAS钻石的王女' 
rd /s/q 'G:\comic\src\res\adatto' 
rd /s/q 'G:\comic\src\res\Admiral Elegy' 
rd /s/q 'G:\comic\src\res\Admiral March' 
rd /s/q 'G:\comic\src\res\Admiral Requiem' 
rd /s/q 'G:\comic\src\res\adonis amurensis' 
rd /s/q 'G:\comic\src\res\ADVENT CIRNO' 
rd /s/q 'G:\comic\src\res\AD物语' 
rd /s/q 'G:\comic\src\res\AFBY' 
rd /s/q 'G:\comic\src\res\Affair再爱你一次！' 
rd /s/q 'G:\comic\src\res\after 9' 
rd /s/q 'G:\comic\src\res\After 9 hours' 
rd /s/q 'G:\comic\src\res\After Citto' 
rd /s/q 'G:\comic\src\res\After Festival' 
rd /s/q 'G:\comic\src\res\After Gold' 
rd /s/q 'G:\comic\src\res\After summer' 
rd /s/q 'G:\comic\src\res\after that of a bathroom' 
rd /s/q 'G:\comic\src\res\After15立城馆CLASSESS' 
rd /s/q 'G:\comic\src\res\Age35' 
rd /s/q 'G:\comic\src\res\AGEHA -アゲハ-(日文)' 
rd /s/q 'G:\comic\src\res\AH喜欢着你' 
rd /s/q 'G:\comic\src\res\AIDS' 
rd /s/q 'G:\comic\src\res\AIKA ZERO' 
rd /s/q 'G:\comic\src\res\AIR' 
rd /s/q 'G:\comic\src\res\AI之恋' 
rd /s/q 'G:\comic\src\res\AI的遗电子' 
rd /s/q 'G:\comic\src\res\AI骇客任务' 
rd /s/q 'G:\comic\src\res\AKB0048' 
rd /s/q 'G:\comic\src\res\AKB00女学园' 
rd /s/q 'G:\comic\src\res\AKB48杀人事件' 
rd /s/q 'G:\comic\src\res\AKB49' 
rd /s/q 'G:\comic\src\res\AKC' 
rd /s/q 'G:\comic\src\res\AKIRA' 
rd /s/q 'G:\comic\src\res\AKKG' 
rd /s/q 'G:\comic\src\res\ALBOX' 
rd /s/q 'G:\comic\src\res\Aldnoah Zero' 
rd /s/q 'G:\comic\src\res\Aldnoah Zero外传：Twin Gemini' 
rd /s/q 'G:\comic\src\res\Alf Love Story' 
rd /s/q 'G:\comic\src\res\Alice in Woundedland' 
rd /s/q 'G:\comic\src\res\Alice or Alice~妹控哥哥与双子姐妹~' 
rd /s/q 'G:\comic\src\res\ALICE★PARADE' 
rd /s/q 'G:\comic\src\res\alive' 
rd /s/q 'G:\comic\src\res\Alive死囚' 
rd /s/q 'G:\comic\src\res\Alkuaine 桑巴贝吉妖精谭' 
rd /s/q 'G:\comic\src\res\All for you' 
rd /s/q 'G:\comic\src\res\All I NEED' 
rd /s/q 'G:\comic\src\res\All My Loving' 
rd /s/q 'G:\comic\src\res\ALL NIGHT LONG' 
rd /s/q 'G:\comic\src\res\All night One night' 
rd /s/q 'G:\comic\src\res\All Right' 
rd /s/q 'G:\comic\src\res\All Things You Want' 
rd /s/q 'G:\comic\src\res\alotof' 
rd /s/q 'G:\comic\src\res\Alp Switch' 
rd /s/q 'G:\comic\src\res\alpha zone' 
rd /s/q 'G:\comic\src\res\Am I a hero？' 
rd /s/q 'G:\comic\src\res\AMAoh-love me tender' 
rd /s/q 'G:\comic\src\res\AMASAKI PRESS' 
rd /s/q 'G:\comic\src\res\amato amaro被爱与苦涩' 
rd /s/q 'G:\comic\src\res\Amaz Mix' 
rd /s/q 'G:\comic\src\res\AMBER' 
rd /s/q 'G:\comic\src\res\Ame-Comi系列3：德拉丹特' 
rd /s/q 'G:\comic\src\res\Americano-exodus' 
rd /s/q 'G:\comic\src\res\American幽灵杰克' 
rd /s/q 'G:\comic\src\res\American幽灵杰克第二部' 
rd /s/q 'G:\comic\src\res\AMETORA雨寅' 
rd /s/q 'G:\comic\src\res\Amnesia Crowd' 
rd /s/q 'G:\comic\src\res\AMNESIA LATER' 
rd /s/q 'G:\comic\src\res\Amour pur' 
rd /s/q 'G:\comic\src\res\An Always Available Man 愿此夜长明' 
rd /s/q 'G:\comic\src\res\An die Freude' 
rd /s/q 'G:\comic\src\res\and boyfriend' 
rd /s/q 'G:\comic\src\res\And-兼职' 
rd /s/q 'G:\comic\src\res\Andante' 
rd /s/q 'G:\comic\src\res\ANDROMALIUS' 
rd /s/q 'G:\comic\src\res\Ange Vierge' 
rd /s/q 'G:\comic\src\res\Ange Vierge cross L.I.N.K.s' 
rd /s/q 'G:\comic\src\res\Ange Vierge Linkage' 
rd /s/q 'G:\comic\src\res\Angel Beats！-The Last Operation-' 
rd /s/q 'G:\comic\src\res\Angel Dust Neo' 
rd /s/q 'G:\comic\src\res\Angel game~再见与未来的碎片~' 
rd /s/q 'G:\comic\src\res\Angel gameⅡ～Rebirth～' 
rd /s/q 'G:\comic\src\res\Angel Heart' 
rd /s/q 'G:\comic\src\res\ANGEL PARA BELLUM' 
rd /s/q 'G:\comic\src\res\Angel-Sky' 
rd /s/q 'G:\comic\src\res\ANGEL-VOICE天使的咆哮' 
rd /s/q 'G:\comic\src\res\Angela' 
rd /s/q 'G:\comic\src\res\angelic syndrome' 
rd /s/q 'G:\comic\src\res\Angle Beats -Operation Wars-' 
rd /s/q 'G:\comic\src\res\ANI-KAN' 
rd /s/q 'G:\comic\src\res\Animal Panic！' 
rd /s/q 'G:\comic\src\res\anime95.2' 
rd /s/q 'G:\comic\src\res\ANIMORED！！' 
rd /s/q 'G:\comic\src\res\Anne Freaks' 
rd /s/q 'G:\comic\src\res\Annihilators' 
rd /s/q 'G:\comic\src\res\Anorexia' 
rd /s/q 'G:\comic\src\res\Another' 
rd /s/q 'G:\comic\src\res\Another Dark' 
rd /s/q 'G:\comic\src\res\Another me' 
rd /s/q 'G:\comic\src\res\Another place on earth' 
rd /s/q 'G:\comic\src\res\answer' 
rd /s/q 'G:\comic\src\res\answerA' 
rd /s/q 'G:\comic\src\res\Anti Romance' 
rd /s/q 'G:\comic\src\res\ap the best' 
rd /s/q 'G:\comic\src\res\APH[米英]いぎろいど眉音本' 
rd /s/q 'G:\comic\src\res\Apollo-阿波罗-' 
rd /s/q 'G:\comic\src\res\Apple Day Dream' 
rd /s/q 'G:\comic\src\res\APPLE苹果' 
rd /s/q 'G:\comic\src\res\April' 
rd /s/q 'G:\comic\src\res\AQUAmariners' 
rd /s/q 'G:\comic\src\res\Aquarium' 
rd /s/q 'G:\comic\src\res\Arachnid' 
rd /s/q 'G:\comic\src\res\ARAGO' 
rd /s/q 'G:\comic\src\res\ARANA-蜘蛛' 
rd /s/q 'G:\comic\src\res\Arasa OL' 
rd /s/q 'G:\comic\src\res\ARCANA事件薄' 
rd /s/q 'G:\comic\src\res\Archetype' 
rd /s/q 'G:\comic\src\res\Archetype Toys' 
rd /s/q 'G:\comic\src\res\Area D异能领域' 
rd /s/q 'G:\comic\src\res\Arena 疯狂男身女模' 
rd /s/q 'G:\comic\src\res\Ares 机战天使' 
rd /s/q 'G:\comic\src\res\Argate Online' 
rd /s/q 'G:\comic\src\res\ARIA Summer' 
rd /s/q 'G:\comic\src\res\ARISA亚里纱' 
rd /s/q 'G:\comic\src\res\ARK ROMANCER' 
rd /s/q 'G:\comic\src\res\Ark 城堡有鬼' 
rd /s/q 'G:\comic\src\res\Armet' 
rd /s/q 'G:\comic\src\res\Armor Amour' 
rd /s/q 'G:\comic\src\res\Around' 
rd /s/q 'G:\comic\src\res\ARTE' 
rd /s/q 'G:\comic\src\res\Artifact' 
rd /s/q 'G:\comic\src\res\ASB封魔九星传' 
rd /s/q 'G:\comic\src\res\Ascribe to heaven' 
rd /s/q 'G:\comic\src\res\Ashen Snown' 
rd /s/q 'G:\comic\src\res\Assassin s Creed' 
rd /s/q 'G:\comic\src\res\assassine' 
rd /s/q 'G:\comic\src\res\Astoria Activate' 
rd /s/q 'G:\comic\src\res\At Home Happy System' 
rd /s/q 'G:\comic\src\res\Ataraxia' 
rd /s/q 'G:\comic\src\res\ATM男' 
rd /s/q 'G:\comic\src\res\Atomic双面兵器少女' 
rd /s/q 'G:\comic\src\res\ATRAIL' 
rd /s/q 'G:\comic\src\res\ATROPA PELLADONNA' 
rd /s/q 'G:\comic\src\res\ATTACK·OF·THE·KILLER' 
rd /s/q 'G:\comic\src\res\Auentura魔法少年' 
rd /s/q 'G:\comic\src\res\Automata' 
rd /s/q 'G:\comic\src\res\AV' 
rd /s/q 'G:\comic\src\res\Avalon 百合短篇合集' 
rd /s/q 'G:\comic\src\res\Avalon~bloom~' 
rd /s/q 'G:\comic\src\res\Avengers A.I' 
rd /s/q 'G:\comic\src\res\Avian Romance' 
rd /s/q 'G:\comic\src\res\AV女优与AV男优的同居生活' 
rd /s/q 'G:\comic\src\res\AV扮演游戏' 
rd /s/q 'G:\comic\src\res\AV游戏' 
rd /s/q 'G:\comic\src\res\AV端指' 
rd /s/q 'G:\comic\src\res\Ayanashi 驱暗者' 
rd /s/q 'G:\comic\src\res\Azur Order' 
rd /s/q 'G:\comic\src\res\A·O·N无敌假面' 
rd /s/q 'G:\comic\src\res\A先辈' 
rd /s/q 'G:\comic\src\res\A君的战争' 
rd /s/q 'G:\comic\src\res\A的剧场B的剧场' 
rd /s/q 'G:\comic\src\res\A科的那个人和B科的我' 
rd /s/q 'G:\comic\src\res\A舰Colle' 
rd /s/q 'G:\comic\src\res\B s LOVEY渴望2013冬' 
rd /s/q 'G:\comic\src\res\B-A-D' 
rd /s/q 'G:\comic\src\res\B-Curse' 
rd /s/q 'G:\comic\src\res\B-TRIAL' 
rd /s/q 'G:\comic\src\res\B-Wanted' 
rd /s/q 'G:\comic\src\res\B.A.W' 
rd /s/q 'G:\comic\src\res\B.P.R.D.' 
rd /s/q 'G:\comic\src\res\Babble Bath Hour' 
rd /s/q 'G:\comic\src\res\BABHEL' 
rd /s/q 'G:\comic\src\res\Baby Blue' 
rd /s/q 'G:\comic\src\res\Baby Doll' 
rd /s/q 'G:\comic\src\res\baby i love you' 
rd /s/q 'G:\comic\src\res\BABY MANY CRY' 
rd /s/q 'G:\comic\src\res\BABY☆I Love You' 
rd /s/q 'G:\comic\src\res\Baby老大' 
rd /s/q 'G:\comic\src\res\BACK STAGE' 
rd /s/q 'G:\comic\src\res\Back to the 科学世纪' 
rd /s/q 'G:\comic\src\res\BAD BOYS' 
rd /s/q 'G:\comic\src\res\Bad Romance' 
rd /s/q 'G:\comic\src\res\BAD ROMANCE2' 
rd /s/q 'G:\comic\src\res\bad sessions' 
rd /s/q 'G:\comic\src\res\BADON' 
rd /s/q 'G:\comic\src\res\BAD_BOYS' 
rd /s/q 'G:\comic\src\res\BAKAMAN' 
rd /s/q 'G:\comic\src\res\BAKUON！！机车娘' 
rd /s/q 'G:\comic\src\res\Balance' 
rd /s/q 'G:\comic\src\res\Balancy Policy平衡政策' 
rd /s/q 'G:\comic\src\res\BALDR DIALOGUE' 
rd /s/q 'G:\comic\src\res\BALDR SKY Dive1' 
rd /s/q 'G:\comic\src\res\balloon panic' 
rd /s/q 'G:\comic\src\res\bambina？' 
rd /s/q 'G:\comic\src\res\BAND MAID' 
rd /s/q 'G:\comic\src\res\BANDY' 
rd /s/q 'G:\comic\src\res\Bang Dream短篇同人漫画系列' 
rd /s/q 'G:\comic\src\res\BanG Dream！Roselia Stage' 
rd /s/q 'G:\comic\src\res\BanG Dream！Sister Festival' 
rd /s/q 'G:\comic\src\res\Bang Dream！同人合集' 
rd /s/q 'G:\comic\src\res\Banker' 
rd /s/q 'G:\comic\src\res\BANKERS赌神' 
rd /s/q 'G:\comic\src\res\BARAGAKIturedure' 
rd /s/q 'G:\comic\src\res\Barnaby says nay and means aye' 
rd /s/q 'G:\comic\src\res\Bath Towel' 
rd /s/q 'G:\comic\src\res\Batman - Harley and Ivy' 
rd /s/q 'G:\comic\src\res\BATMAN-CHILD OF DREAMS' 
rd /s/q 'G:\comic\src\res\BATMAN亡灵书' 
rd /s/q 'G:\comic\src\res\Battery-人体电池和砂之巨像-' 
rd /s/q 'G:\comic\src\res\BATTLE OF TOUHOU' 
rd /s/q 'G:\comic\src\res\BAT×DRAGON' 
rd /s/q 'G:\comic\src\res\BAUMKUCHEN' 
rd /s/q 'G:\comic\src\res\bauxite chips' 
rd /s/q 'G:\comic\src\res\BB.HELL' 
rd /s/q 'G:\comic\src\res\BBA的泳装大会' 
rd /s/q 'G:\comic\src\res\BB战士三国传 战神决斗篇' 
rd /s/q 'G:\comic\src\res\BB战士三国传 英雄激突篇' 
rd /s/q 'G:\comic\src\res\BB石膏像' 
rd /s/q 'G:\comic\src\res\be a slave to love' 
rd /s/q 'G:\comic\src\res\Be Close to Me Ever After' 
rd /s/q 'G:\comic\src\res\be dying for' 
rd /s/q 'G:\comic\src\res\Be MONSTER' 
rd /s/q 'G:\comic\src\res\BE MY DOG？' 
rd /s/q 'G:\comic\src\res\be our guest' 
rd /s/q 'G:\comic\src\res\Bears' 
rd /s/q 'G:\comic\src\res\BEAST COMPLEX' 
rd /s/q 'G:\comic\src\res\BEASTARS' 
rd /s/q 'G:\comic\src\res\Beautiful' 
rd /s/q 'G:\comic\src\res\Beautiful days' 
rd /s/q 'G:\comic\src\res\Beautiful Disaster' 
rd /s/q 'G:\comic\src\res\Beautiful Monday' 
rd /s/q 'G:\comic\src\res\BEAUTIFUL TOMORROW' 
rd /s/q 'G:\comic\src\res\beautiful world' 
rd /s/q 'G:\comic\src\res\beautiful years' 
rd /s/q 'G:\comic\src\res\BEAUTY' 
rd /s/q 'G:\comic\src\res\Beauty.Honey' 
rd /s/q 'G:\comic\src\res\BED' 
rd /s/q 'G:\comic\src\res\bed design' 
rd /s/q 'G:\comic\src\res\Before Story' 
rd /s/q 'G:\comic\src\res\Best Blue' 
rd /s/q 'G:\comic\src\res\BEST PARTNER' 
rd /s/q 'G:\comic\src\res\Bestia' 
rd /s/q 'G:\comic\src\res\Betakuto 拓斗勇往直前' 
rd /s/q 'G:\comic\src\res\between the sheets' 
rd /s/q 'G:\comic\src\res\BF' 
rd /s/q 'G:\comic\src\res\BFC俱乐部' 
rd /s/q 'G:\comic\src\res\BF俱乐部' 
rd /s/q 'G:\comic\src\res\Bianca~喜欢的就是你' 
rd /s/q 'G:\comic\src\res\Biblia古书堂事件薄' 
rd /s/q 'G:\comic\src\res\Big Bang Herone' 
rd /s/q 'G:\comic\src\res\big bar' 
rd /s/q 'G:\comic\src\res\Big Hearts' 
rd /s/q 'G:\comic\src\res\Big Order' 
rd /s/q 'G:\comic\src\res\Bigger Hunter' 
rd /s/q 'G:\comic\src\res\BigHearts' 
rd /s/q 'G:\comic\src\res\Billion Dogs' 
rd /s/q 'G:\comic\src\res\BILLY BAT' 
rd /s/q 'G:\comic\src\res\Biorg Trinity' 
rd /s/q 'G:\comic\src\res\BIRTH The Lunar Taker' 
rd /s/q 'G:\comic\src\res\Birthday：G' 
rd /s/q 'G:\comic\src\res\BIRTH诞生' 
rd /s/q 'G:\comic\src\res\Bitter' 
rd /s/q 'G:\comic\src\res\BITTER CHOCOLATE' 
rd /s/q 'G:\comic\src\res\Bitter Sugar' 
rd /s/q 'G:\comic\src\res\Bitter Sweet' 
rd /s/q 'G:\comic\src\res\bitter ver' 
rd /s/q 'G:\comic\src\res\BITTER跟他的亲蜜接吻' 
rd /s/q 'G:\comic\src\res\Bitter＆Sweet' 
rd /s/q 'G:\comic\src\res\BL48手' 
rd /s/q 'G:\comic\src\res\BLACK BOX' 
rd /s/q 'G:\comic\src\res\BLACK DIAMOND' 
rd /s/q 'G:\comic\src\res\Black Lack(日文)' 
rd /s/q 'G:\comic\src\res\Black Leopard' 
rd /s/q 'G:\comic\src\res\Black Order' 
rd /s/q 'G:\comic\src\res\BLACK SHOES' 
rd /s/q 'G:\comic\src\res\Black X Black' 
rd /s/q 'G:\comic\src\res\Blacksad issue' 
pause